### ISSUE TITLE
Která strana je Master a která Slave?

### ISSUE THREAD

**Issue by slimonslimon** [ThunderFly-aerospace/TFI2CEXT01#6]
Jak má být zařízení správně připojeno? Nebo je to jedno?

**Comment by kaklik** [comment]
Pokusil jsem se to teď naznačit do potisku.

![image](https://user-images.githubusercontent.com/1194177/120937760-8b462900-c70f-11eb-9b8a-39605c9793ad.png)

Ale moc se mi to řešení nelíbí. Kdyby někdo měl nějaký lepší nápad, tak by to mohlo být užitečný. 

Zároveň jsem to [popsal do readme](https://github.com/ThunderFly-aerospace/TFI2CEXT01#connection).

**Comment by ChroustJan** [comment]
Popisky aplikovány ve verzi 01B
